use actix_web::{get, Responder};
#[get("/")]
async fn index() -> impl Responder {
    "
    Available routes:
        - GET /ping\t\t\t\t --> pong
        - GET /startnewlog\t\t\t --> start a new log file
        - GET /play/{audio_file_name}\t\t --> play the audio file
        - GET /tone/{freq}/{duration}/{amplitude}/{sample_rate} 
        \t\t\t\t\t\t\t--> play a pure sine tone
        - GET /save_tone/{freq}/{duration}/{amplitude}/{sample_rate}
        \t\t\t\t\t\t\t--> create a .wav file of a pure sine tone
        - GET /generate_batch_files\t\t --> generate a .zip containing batch files to request the audio files (close when audio file is finished playing)
        - GET /generate_batch_files_async\t --> generate a .zip containing batch files to request the audio files (asynchronous, close immediately)

    Note:
        - The batch files generated by /generate_batch_files and /generate_batch_files_async are for Windows only.
        - For /tone, freq is in Hz, duration is in milliseconds, amplitude is in dB, and sample_rate is in Hz.
    "
}